-- MySQL Script generated by MySQL Workbench
-- 10/02/14 01:27:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oficina_mecanica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina_mecanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina_mecanica` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `oficina_mecanica` ;

-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(9) NOT NULL,
  `dtNacimento` DATE NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `ano` DATE NOT NULL,
  `placa` VARCHAR(8) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `fk_Veiculo_Cliente_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `oficina_mecanica`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Tipo_Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Tipo_Servicos` (
  `idTipo_Servicos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idLogin`, `idCliente`),
  INDEX `fk_Login_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Login_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `oficina_mecanica`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Ent_Sai_Veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Ent_Sai_Veiculos` (
  `idEnt_Sai_Veiculos` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `dtEntrada` DATE NULL,
  `dtSaida` DATE NULL,
  PRIMARY KEY (`idEnt_Sai_Veiculos`),
  INDEX `fk_Ent_Sai_Veiculos_Veiculo1_idx` (`idVeiculo` ASC),
  CONSTRAINT `fk_Ent_Sai_Veiculos_Veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `oficina_mecanica`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Ordem_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Ordem_Servico` (
  `idOrdem_Servico` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idOrdem_Servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `descrição` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `dtHora` DATETIME NOT NULL,
  `idEnt_Sai_Veiculos` INT NOT NULL,
  `idTipo_Servicos` INT NOT NULL,
  `idOrdem_Servico` INT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idServicos`, `descrição`),
  INDEX `fk_Servicos_Ent_Sai_Veiculos1_idx` (`idEnt_Sai_Veiculos` ASC),
  INDEX `fk_Servicos_Tipo_Servicos1_idx` (`idTipo_Servicos` ASC),
  INDEX `fk_Servicos_Ordem_Servico1_idx` (`idOrdem_Servico` ASC),
  CONSTRAINT `fk_Servicos_Ent_Sai_Veiculos1`
    FOREIGN KEY (`idEnt_Sai_Veiculos`)
    REFERENCES `oficina_mecanica`.`Ent_Sai_Veiculos` (`idEnt_Sai_Veiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicos_Tipo_Servicos1`
    FOREIGN KEY (`idTipo_Servicos`)
    REFERENCES `oficina_mecanica`.`Tipo_Servicos` (`idTipo_Servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicos_Ordem_Servico1`
    FOREIGN KEY (`idOrdem_Servico`)
    REFERENCES `oficina_mecanica`.`Ordem_Servico` (`idOrdem_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`Orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`Orcamento` (
  `idOrcamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `idOrdem_Servico` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idOrcamento`, `idOrdem_Servico`),
  INDEX `fk_Orcamento_Ordem_Servico1_idx` (`idOrdem_Servico` ASC),
  CONSTRAINT `fk_Orcamento_Ordem_Servico1`
    FOREIGN KEY (`idOrdem_Servico`)
    REFERENCES `oficina_mecanica`.`Ordem_Servico` (`idOrdem_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
